/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HospitalReceptionist;

import UI.HospitalDoctor.*;
import UI.DiagnosticsSystemAdmin.*;
import UI.AmbulanceSystemAdmin.*;
import UI.SystemAdmin.*;
import ApplicationSystem.ApplicationSystem;
import Roles.PatientRole;
import User.UserAccount;
import com.github.javafaker.Faker;
import javax.swing.JOptionPane;

/**
 *
 * @author rushita
 */
public class ResCreatePatient extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    public ResCreatePatient(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        setFakeData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        bpField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        jLabel14.setBackground(new java.awt.Color(54, 125, 118));
        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CREATE PATIENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1434, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DETAILS");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 195, 40));

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 195, 37));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 195, 37));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/padlock.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 40, 37));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/user (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 40, 37));

        createBtn.setBackground(new java.awt.Color(204, 204, 255));
        createBtn.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        createBtn.setText("CREATE");
        createBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 195, 32));

        bpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpFieldActionPerformed(evt);
            }
        });
        add(bpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 195, 37));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/bp-operator.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 40, 37));

        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 195, 37));

        weightField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightFieldActionPerformed(evt);
            }
        });
        add(weightField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 195, 37));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HospitalReceptionist/age-limit.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 40, 37));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/weight.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 40, 37));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/card (1).gif"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 1020, 440));

        jLabel7.setFont(new java.awt.Font("Charter", 0, 18)); // NOI18N
        jLabel7.setText("Weight");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Charter", 0, 18)); // NOI18N
        jLabel8.setText("BP");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Charter", 0, 18)); // NOI18N
        jLabel9.setText("Age");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if(userNameField.getText().isEmpty()||passwordField.getText().isEmpty()|| bpField.getText().isEmpty() || ageField.getText().isEmpty() || weightField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required");
        }
        else{
            String userName = userNameField.getText();
            double weight = Double.parseDouble(weightField.getText()); // Parse the weight as double

            if(this.applicationSystem.getPatientUserAccountDirectory().getPatientDetailDirectory().checkUniqueUsername(userName)){
                this.applicationSystem.getPatientUserAccountDirectory().getPatientDetailDirectory().userAccountCreation(userNameField.getText(), passwordField.getText(), new PatientRole(), bpField.getText(), Double.valueOf(ageField.getText()), weight);
                //System.out.println("HI"+ this.applicationSystem.getHospitalUserAccountDirectory().getHospitaluseraccountlist().size());
                JOptionPane.showMessageDialog(null, "Created New Patient");
            }else{
                JOptionPane.showMessageDialog(null, "Patient with same credentials already exists");
            }
        }
        userNameField.setText("");
        passwordField.setText("");
        bpField.setText("");
        ageField.setText("");
        weightField.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    private void bpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpFieldActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void weightFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField bpField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables

    private void setFakeData() {
        Faker faker = new Faker();
        String fakeUserName = faker.name().username(); // Random username
        String fakePassword = faker.internet().password(); // Random password
        String fakeBp = faker.number().numberBetween(80, 120) + "/" + faker.number().numberBetween(60, 90); // Random BP
        int fakeAge = faker.number().numberBetween(1, 100); // Random age
        double fakeWeight = faker.number().randomDouble(2, 10, 200); // Random weight (with 2 decimal places, between 10 and 200)

        userNameField.setText(fakeUserName);
        passwordField.setText(fakePassword);
        bpField.setText(fakeBp);
        ageField.setText(String.valueOf(fakeAge));
        weightField.setText(String.format("%.2f", fakeWeight));
    }
}
