 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AmbulancePOC;

import Ambulance.AssignedVehicles;
import Ambulance.Driver;
import Ambulance.Vehicle;
import UI.DiagnosticsSystemAdmin.*;
import UI.AmbulanceSystemAdmin.*;
import UI.SystemAdmin.*;
import ApplicationSystem.ApplicationSystem;
import UI.AmbulanceDriver.DriverVehicleRequest;
import User.UserAccount;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rushita
 */
public class POCAssignDrivers extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    DefaultTableModel vehicleTableModel;
    DefaultTableModel DriverTableModel;
    DefaultTableModel ADTableModel;
    public POCAssignDrivers(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        this.vehicleTableModel = (DefaultTableModel) tblName.getModel();
        this.DriverTableModel = (DefaultTableModel) tblDriver.getModel();
        this.ADTableModel = (DefaultTableModel) tblVehicleDriver.getModel();
        populateTable();
        populateDrivers();
        tblName.setDefaultRenderer(Object.class, new MyCellRenderer());
        tblDriver.setDefaultRenderer(Object.class, new MyCellRenderer());
        tblVehicleDriver.setDefaultRenderer(Object.class, new MyCellRenderer());
        
    }
    
    private class MyCellRenderer extends DefaultTableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (row % 2 == 0) {
                c.setBackground(new Color(204, 204, 255)); 
            } else {
                c.setBackground(new Color(204, 204, 255)); 
            }
            return c;
        }
    }
    
    public void populateTable(){
        vehicleTableModel.setRowCount(0);
        for(Vehicle vehicle : applicationSystem.getAmbulanceDirectory().getVehicleDirectory().getVehicle()){
            Object rows[] = new Object[2];
            rows[0] = vehicle.getNumber();
            rows[1] = vehicle.getName();
            
            vehicleTableModel.addRow(rows);
        }
    }
    
    public void populateDrivers(){
        DriverTableModel.setRowCount(0);
        for(Driver driver: applicationSystem.getAmbulanceDirectory().getDriverUserDirectory().getUseraccountlist()){
            Object rows[] = new Object[1];
            rows[0] = driver.getUserName();
            
            DriverTableModel.addRow(rows);
        }
    }
    
    public void populateadTable(){
        ADTableModel.setRowCount(0);
        for(AssignedVehicles av: applicationSystem.getAmbulanceDirectory().getAssignedVehiclesDirectory().getAssignedVehicles()){
            Object rows[] = new Object[2];
            rows[0] = av.getVehicle().getName();
            rows[1] = av.getDriver().getUserName();
            
            ADTableModel.addRow(rows);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAssignDrivers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblName = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDriver = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVehicleDriver = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        lblAssignDrivers.setBackground(new java.awt.Color(54, 125, 118));
        lblAssignDrivers.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblAssignDrivers.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignDrivers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssignDrivers.setText("ASSIGN DRIVERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAssignDrivers, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAssignDrivers)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 100));

        tblName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblName);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 300, 220));

        tblDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDriver);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 310, 220));

        btnAssign.setBackground(new java.awt.Color(204, 204, 255));
        btnAssign.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnAssign.setText("ASSIGN");
        btnAssign.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 110, 30));

        tblVehicleDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle", "Driver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVehicleDriver);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 320, 220));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/male-paramedic-and-ambulance-van-6834850-5662135.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1000, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        int row = tblName.getSelectedRow();
        int driverrow = tblDriver.getSelectedRow();
        
        if(row == -1)
        {
            JOptionPane.showMessageDialog(null,"Please select a Vehicle", "Select Warning", 2);
            
        }
        
        if(driverrow == -1){
            JOptionPane.showMessageDialog(null,"Please select a Driver", "Select Warning", 2);
        }
        
        
        ArrayList<AssignedVehicles> allAssignedVehciles = applicationSystem.getAmbulanceDirectory().getAssignedVehiclesDirectory().getAssignedVehicles();
        Vehicle vehicle = applicationSystem.getAmbulanceDirectory().getVehicleDirectory().getVehicle().get(row);
        Driver driver = applicationSystem.getAmbulanceDirectory().getDriverUserDirectory().getUseraccountlist().get(driverrow);

        
        for(AssignedVehicles assignedVehicle : allAssignedVehciles)
        {
            
           if(assignedVehicle.getDriver().getUserName().equals(driver.getUserName()))
           {
                JOptionPane.showMessageDialog(null, "Driver already assigned. please select another driver.");
                return;
           }
           if(assignedVehicle.getVehicle().getNumber() == vehicle.getNumber())
           {
               JOptionPane.showMessageDialog(null, "vehicle is already assigned. please select another vehicle.");
                return;
           }
            
        }
        AssignedVehicles assignedVehicles = applicationSystem.getAmbulanceDirectory().getAssignedVehiclesDirectory().assignedVehicleDetail(vehicle, driver);

        JOptionPane.showMessageDialog(null, "Successfully Assigned Driver");

        
        populateadTable();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAssignDrivers;
    private javax.swing.JTable tblDriver;
    private javax.swing.JTable tblName;
    private javax.swing.JTable tblVehicleDriver;
    // End of variables declaration//GEN-END:variables
}
