/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AmbulancePOC;

import Ambulance.Vehicle;
import UI.DiagnosticsSystemAdmin.*;
import UI.AmbulanceSystemAdmin.*;
import UI.SystemAdmin.*;
import ApplicationSystem.ApplicationSystem;
import UI.AmbulanceDriver.DriverVehicleRequest;
import User.UserAccount;
import com.github.javafaker.Faker;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rushita
 */
public class POCCreateVehicles extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    DefaultTableModel vehicleTableModel;
    public POCCreateVehicles(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        this.vehicleTableModel = (DefaultTableModel) tbldetails.getModel();
        setFakeData();

        populateTable();
        tbldetails.setDefaultRenderer(Object.class, new MyCellRenderer());
    }

    private void setFakeData() {
        Faker faker = new Faker();
        int fakeNumber = faker.number().numberBetween(1000, 9999); // Random vehicle number
        String fakeName = faker.company().name() + " Model " + faker.number().numberBetween(100, 999); // Random vehicle name (or other suitable method)

        txtVehicleNumber.setText(String.valueOf(fakeNumber));
        txtVehicleName.setText(fakeName);
    }
    
    private class MyCellRenderer extends DefaultTableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (row % 2 == 0) {
                c.setBackground(new Color(204, 204, 255)); 
            } else {
                c.setBackground(new Color(204, 204, 255)); 
            }
            return c;
        }
    }
    
    
    public void populateTable(){
        vehicleTableModel.setRowCount(0);
        for(Vehicle vehicle : applicationSystem.getAmbulanceDirectory().getVehicleDirectory().getVehicle()){
            Object rows[] = new Object[2];
            rows[0] = vehicle.getNumber();
            rows[1] = vehicle.getName();
            
            vehicleTableModel.addRow(rows);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateVehicle = new javax.swing.JLabel();
        txtVehicleNumber = new javax.swing.JTextField();
        txtVehicleName = new javax.swing.JTextField();
        lblVehicleNumber = new javax.swing.JLabel();
        lblVehicleName = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        lblCreateVehicle.setBackground(new java.awt.Color(56, 16, 151));
        lblCreateVehicle.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblCreateVehicle.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateVehicle.setText("CREATE VEHICLES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCreateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCreateVehicle)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, -1));
        add(txtVehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 30));

        txtVehicleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNameActionPerformed(evt);
            }
        });
        add(txtVehicleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, 30));

        lblVehicleNumber.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        lblVehicleNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleNumber.setText("Vehicle Number :");
        add(lblVehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 30));

        lblVehicleName.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        lblVehicleName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicleName.setText("Vehicle Name :");
        add(lblVehicleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 30));

        btnCreate.setBackground(new java.awt.Color(204, 204, 255));
        btnCreate.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnCreate.setText("CREATE");
        btnCreate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 30));

        tbldetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 700, 210));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/dcd79fc7784d5e2d2686058c6073cee3.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 1000, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(txtVehicleNumber.getText().isEmpty()||txtVehicleName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are Compulsory");
        }
        else{
            int number = Integer.valueOf(txtVehicleNumber.getText());
            
            if(this.applicationSystem.getAmbulanceDirectory().getVehicleDirectory().checkUniqueVehicleNumber(number)){
                     this.applicationSystem.getAmbulanceDirectory().getVehicleDirectory().createVehicle(number,txtVehicleName.getText());
                     //System.out.println("HI"+ this.applicationSystem.getHospitalUserAccountDirectory().getHospitaluseraccountlist().size());
                     JOptionPane.showMessageDialog(null, "Created New Vehicle");
                 }else{
                        JOptionPane.showMessageDialog(null, "Vehicle with Same Number already exists");
                 }
        }
        populateTable();
        
        txtVehicleNumber.setText("");
        txtVehicleName.setText("");
        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateVehicle;
    private javax.swing.JLabel lblVehicleName;
    private javax.swing.JLabel lblVehicleNumber;
    private javax.swing.JTable tbldetails;
    private javax.swing.JTextField txtVehicleName;
    private javax.swing.JTextField txtVehicleNumber;
    // End of variables declaration//GEN-END:variables
}
