/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.AmbulanceSystemAdmin;

import ApplicationSystem.ApplicationSystem;
import UI.AmbulanceLogin.AmbulanceLoginJFrame;
import UI.MainJFrame;
import User.UserAccount;

/**
 *
 * @author rushita
 */
public class AmbulanceSystemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AmbulanceSystemAdmin
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    public AmbulanceSystemAdmin(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        createDriverBtn = new javax.swing.JButton();
        createPOCBtn = new javax.swing.JButton();
        viewwUserBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewUserBtn = new javax.swing.JButton();
        updateUserBtn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1280, 640));

        jPanel1.setBackground(new java.awt.Color(125, 125, 199));
        jPanel1.setMinimumSize(new java.awt.Dimension(240, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createDriverBtn.setBackground(new java.awt.Color(204, 204, 255));
        createDriverBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        createDriverBtn.setText("CREATE DRIVERS");
        createDriverBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDriverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createDriverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 40));

        createPOCBtn.setBackground(new java.awt.Color(204, 204, 255));
        createPOCBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        createPOCBtn.setText("CREATE POCs");
        createPOCBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createPOCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPOCBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createPOCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 40));

        viewwUserBtn.setBackground(new java.awt.Color(204, 204, 255));
        viewwUserBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        viewwUserBtn.setText("VIEW USERS");
        viewwUserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewwUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewwUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewwUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 210, 40));

        logoutBtn.setBackground(new java.awt.Color(204, 204, 255));
        logoutBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-logout-25.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 29, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-system-administrator-male-96.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        viewUserBtn.setBackground(new java.awt.Color(204, 204, 255));
        viewUserBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        viewUserBtn.setText("DASHBOARD");
        viewUserBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 40));

        updateUserBtn1.setBackground(new java.awt.Color(204, 204, 255));
        updateUserBtn1.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        updateUserBtn1.setText("UPDATE USERS");
        updateUserBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateUserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(updateUserBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 210, 40));

        jLabel6.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Hello, Ambulance Admin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(124, 124, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AMBULANCE SYSTEM ADMIN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1190, 50));

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/ambpic.gif"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 760, 810));

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDriverBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AmbCreateDriver(this.applicationSystem, this.userAccount));
    }//GEN-LAST:event_createDriverBtnActionPerformed

    private void createPOCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPOCBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AmbCreatePOC(this.applicationSystem, this.userAccount));
    }//GEN-LAST:event_createPOCBtnActionPerformed

    private void viewwUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewwUserBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AmbDelete(this.applicationSystem, this.userAccount));
    }//GEN-LAST:event_viewwUserBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AmbulanceLoginJFrame aj = new AmbulanceLoginJFrame(this.applicationSystem, this.userAccount);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AmbView(this.applicationSystem, this.userAccount));
    }//GEN-LAST:event_viewUserBtnActionPerformed

    private void updateUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtn1ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AmbUpdate(this.applicationSystem, this.userAccount));
    }//GEN-LAST:event_updateUserBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmbulanceSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmbulanceSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmbulanceSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmbulanceSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AmbulanceSystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDriverBtn;
    private javax.swing.JButton createPOCBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton updateUserBtn1;
    private javax.swing.JButton viewUserBtn;
    private javax.swing.JButton viewwUserBtn;
    // End of variables declaration//GEN-END:variables
}
