/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import ApplicationSystem.ApplicationSystem;
import Roles.AmbulanceSystemAdminRole;
import Roles.DiagnosticSystemAdminRole;
import Roles.HospitalSystemAdminRole;
import Roles.PharmacySystemAdminRole;
import Roles.Role;
import User.UserAccount;
import User.UserValidationService;
import javax.swing.JOptionPane;

/**
 *
 * @author rushita
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    
    
    public CreateJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        
        populateDropdown();
    }
    
    public void populateDropdown() {
        jComboBox1.removeAllItems();
        for (String rolename : Role.getAllRoles()) {
            jComboBox1.addItem(rolename);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        jLabel14.setBackground(new java.awt.Color(54, 125, 118));
        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CREATE USERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/user (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CREDENTIALS");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/padlock.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 40, 40));

        userNameField.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 240, 36));

        passwordField.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 240, 37));

        jComboBox1.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 240, 40));

        createBtn.setBackground(new java.awt.Color(204, 204, 255));
        createBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        createBtn.setText("CREATE");
        createBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/usercreation.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 760, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
         String userName = userNameField.getText();
         String password = passwordField.getText();
         UserValidationService validationService = new UserValidationService();

        if(userNameField.getText().isEmpty()||passwordField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are Required");
        }
        if (!validationService.isValidUsername(userName)) {
        JOptionPane.showMessageDialog(null, "Invalid username. It should be 3-15 characters, starting with a letter.");
        return;
    }
    
    if (!validationService.isStrongPassword(password)) {
        String passwordMessage = validationService.getPasswordValidationMessage(password);
        JOptionPane.showMessageDialog(null, passwordMessage);
        return;
    }
        try{
            //creating hospitalsystemadmin
            if(jComboBox1.getSelectedItem().equals("hospital system admin")){
                 if(this.applicationSystem.getHospitalDirectory().checkingUniqueUserName(userName)){
                     this.applicationSystem.getHospitalDirectory().userAccountCreation(userNameField.getText(), passwordField.getText(), new HospitalSystemAdminRole());
                     //System.out.println("HI"+ this.applicationSystem.getHospitalUserAccountDirectory().getHospitaluseraccountlist().size());
                     JOptionPane.showMessageDialog(null, "Created New Hospital Admin");
                 }else{
                        JOptionPane.showMessageDialog(null, "Hospital Admin with same credentials already exists");
                 }
             }
            //creating ambulancesystemadmin
            if(jComboBox1.getSelectedItem().equals("ambulance system admin")){
                 if(this.applicationSystem.getAmbulanceDirectory().checkingUniqueUserName(userName)){
                     this.applicationSystem.getAmbulanceDirectory().userAccountCreation(userNameField.getText(), passwordField.getText(), new AmbulanceSystemAdminRole());
                     JOptionPane.showMessageDialog(null, "Created New Ambulance Admin");
                 }else{
                        JOptionPane.showMessageDialog(null, "Ambulance Admin with same credentials already exists");
                 }
             }
            //creating pharmacysystemadmin
            if(jComboBox1.getSelectedItem().equals("pharmacy system admin")){
                 if(this.applicationSystem.getPharmacyUsersDirectory().checkingUniqueUsername(userName)){
                     this.applicationSystem.getPharmacyUsersDirectory().userAccountCreation(userNameField.getText(), passwordField.getText(), new PharmacySystemAdminRole());
                     JOptionPane.showMessageDialog(null, "Created New Pharmacy Admin");
                 }else{
                        JOptionPane.showMessageDialog(null, "Pharmacy Admin with same credentials already exists");
                 }
             }
            //creating diagnosticsystemadmin
            if(jComboBox1.getSelectedItem().equals("diagnostic system admin")){
                 if(this.applicationSystem.getDiagnosticUsersDirectory().checkingUniqueUserName(userName)){
                     this.applicationSystem.getDiagnosticUsersDirectory().userAccountCreation(userNameField.getText(), passwordField.getText(), new DiagnosticSystemAdminRole());
                     JOptionPane.showMessageDialog(null, "Created New Diagnostic Admin");
                 }else{
                        JOptionPane.showMessageDialog(null, "Diagnostic Admin with same credentials already exists");
                 }
             }
        }catch (Exception e) {
       JOptionPane.showMessageDialog(null, "An error occurred while creating acccount : " + e.getMessage());
    }
      userNameField.setText("");
      passwordField.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
