/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import Ambulance.Driver;
import ApplicationSystem.ApplicationSystem;
import Roles.AmbulanceSystemAdminRole;
import Roles.DiagnosticSystemAdminRole;
import Roles.HospitalSystemAdminRole;
import Roles.PharmacySystemAdminRole;
import UI.AmbulanceSystemAdmin.AmbUpdate;
import User.UserAccount;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rushita
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    DefaultTableModel usersTableModel;
    public UpdateJPanel(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.applicationSystem = applicationSystem;
        this.userAccount = userAccount;
        this.usersTableModel = (DefaultTableModel) jTable2.getModel();
        jTable2.setDefaultRenderer(Object.class, new MyCellRenderer());
        PopulateTable();
    }
    
    private class MyCellRenderer extends DefaultTableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (row % 2 == 0) {
                c.setBackground(new Color(204, 204, 255)); 
            } else {
                c.setBackground(new Color(204, 204, 255)); 
            }
            return c;
        }
    }
    
    
    public ArrayList<UserAccount> getUserAccount()
    {
        
        ArrayList<UserAccount> userAccounts = new ArrayList<>();

    if (jComboBox1.getSelectedItem().equals("Hospital System Admin")) {
        if (applicationSystem.getHospitalDirectory().getHealthCareRegistry() != null) {
            userAccounts = applicationSystem.getHospitalDirectory().getHealthCareRegistry();
        }
    } else if (jComboBox1.getSelectedItem().equals("Ambulance System Admin")) {
        if (applicationSystem.getAmbulanceDirectory().getAmbulanceuseraccountlist() != null) {
            userAccounts = applicationSystem.getAmbulanceDirectory().getAmbulanceuseraccountlist();
        }
    } else if (jComboBox1.getSelectedItem().equals("Pharmacy System Admin")) {
        if (applicationSystem.getPharmacyUsersDirectory().getPharmacyUserList() != null) {
            userAccounts = applicationSystem.getPharmacyUsersDirectory().getPharmacyUserList();
        }
    } else if (jComboBox1.getSelectedItem().equals("Diagnostic System Admin")) {
        if (applicationSystem.getDiagnosticUsersDirectory().getDiagnosticUserList() != null) {
            userAccounts = applicationSystem.getDiagnosticUsersDirectory().getDiagnosticUserList();
        }
    }

    return userAccounts;
    }
    public void PopulateTable(){
        
        
        usersTableModel.setRowCount(0);
        ArrayList<UserAccount> userAccounts  = getUserAccount();
             
         for(UserAccount ua: userAccounts)
         {
             Object rows[] = new Object[2];
            rows[0] = ua.getUserName();
            rows[1] = ua.getPassword();
            
            usersTableModel.addRow(rows);
         }
        
         
        
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        createBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        jLabel14.setBackground(new java.awt.Color(56, 16, 151));
        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("UPDATE USERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostic System Admin", "Ambulance System Admin", "Pharmacy System Admin", "Hospital System Admin" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 980, 220));
        add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 260, 30));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 260, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/padlock.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/user (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        createBtn.setBackground(new java.awt.Color(204, 204, 255));
        createBtn.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        createBtn.setText("UPDATE");
        createBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 121, 32));

        createBtn1.setBackground(new java.awt.Color(204, 204, 255));
        createBtn1.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        createBtn1.setText("SELECT");
        createBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn1ActionPerformed(evt);
            }
        });
        add(createBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 121, 32));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMINS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 140, 30));

        jLabel4.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/updateadmin.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 1000, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
            
        if(userNameField.getText().isEmpty()||passwordField.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All Fields are Compulsory");
        }
        else{
            int row = jTable2.getSelectedRow();
             ArrayList<UserAccount> userAccounts  = getUserAccount();
             
            userAccount = userAccounts.get(row);
            userAccount.setUserName(userNameField.getText());
            userAccount.setPassword(passwordField.getText());
           
            
            PopulateTable();
            
            JOptionPane.showMessageDialog(null, "Updated");
        }
        userNameField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    private void createBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn1ActionPerformed
        int row = jTable2.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }
         ArrayList<UserAccount> userAccounts  = getUserAccount();
         
        userAccount = userAccounts.get(row);
        userNameField.setText(userAccount.getUserName());
        passwordField.setText(userAccount.getPassword());
    }//GEN-LAST:event_createBtn1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        PopulateTable();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createBtn1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
