/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import ApplicationSystem.ApplicationSystem;
import UI.AmbulanceLogin.AmbulanceLoginJFrame;
import UI.DiagnosticsLogin.DiagnosticsLoginJFrame;
import UI.HospitalLogin.HospitalLoginJFrame;
import UI.PharmacyLogin.PharmacyLoginJFrame;
import User.UserAccount;
import javax.swing.JOptionPane;
import com.github.javafaker.Faker;

/**
 *
 * @author rushita
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;

    public MainJFrame() {
        initComponents();
        this.setVisible(true);
        
        
        this.applicationSystem = ApplicationSystem.getInstance();
    

        //System.out.println("Main Frame"+this.applicationSystem.getHospitalUserAccountDirectory().getHospitaluseraccountlist().size());

    }
    
    public MainJFrame(ApplicationSystem applicationSystem, UserAccount userAccount){
        initComponents();
        this.setVisible(true);
        
        this.applicationSystem = applicationSystem;
        
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnAmbulance = new javax.swing.JButton();
        btnDiagnostics = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnPharmacy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton8.setBackground(new java.awt.Color(61, 118, 125));
        jButton8.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Hospital");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(144, 144, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/ttt.jpeg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -110, 920, 1120));

        jPanel3.setBackground(new java.awt.Color(56, 16, 151));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBackground(new java.awt.Color(56, 16, 151));
        txtUserName.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, 41));

        txtPassword.setBackground(new java.awt.Color(56, 16, 151));
        txtPassword.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 41));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 230, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 230, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-lock-24.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 30, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-user-24.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 30, -1));

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 30));

        btnAmbulance.setBackground(new java.awt.Color(204, 204, 255));
        btnAmbulance.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnAmbulance.setText("Ambulance");
        btnAmbulance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbulanceActionPerformed(evt);
            }
        });
        jPanel3.add(btnAmbulance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 210, 50));

        btnDiagnostics.setBackground(new java.awt.Color(204, 204, 255));
        btnDiagnostics.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnDiagnostics.setText("Diagnostics");
        btnDiagnostics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDiagnostics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticsActionPerformed(evt);
            }
        });
        jPanel3.add(btnDiagnostics, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, 210, 50));

        btnHospital.setBackground(new java.awt.Color(204, 204, 255));
        btnHospital.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnHospital.setText("Hospital");
        btnHospital.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });
        jPanel3.add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 210, 50));

        btnPharmacy.setBackground(new java.awt.Color(204, 204, 255));
        btnPharmacy.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnPharmacy.setText("Pharmacy");
        btnPharmacy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyActionPerformed(evt);
            }
        });
        jPanel3.add(btnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 210, 50));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HealFlow Boston ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Boolean foundUser = false;
        
        if(this.applicationSystem.getUserDirectory().userAuthentication(txtUserName.getText(), txtPassword.getText()) != null){
            UserAccount userAccount = this.applicationSystem.getUserDirectory().userAuthentication(txtUserName.getText(), txtPassword.getText()); 
            foundUser = true;
            userAccount.getUserRole().workAreaCreation(applicationSystem, userAccount);
            this.setVisible(false);   
        }
        
        if(!foundUser) {
              JOptionPane.showMessageDialog(null, "User not found. Please enter valid credentials.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    
                                           

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
        HospitalLoginJFrame h1 = new HospitalLoginJFrame(this.applicationSystem, this.userAccount);
        h1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbulanceActionPerformed
        // TODO add your handling code here:
        AmbulanceLoginJFrame a1 = new AmbulanceLoginJFrame(this.applicationSystem, this.userAccount);
        a1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAmbulanceActionPerformed

    private void btnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyActionPerformed
        // TODO add your handling code here:
        PharmacyLoginJFrame p1 = new PharmacyLoginJFrame(this.applicationSystem, this.userAccount);
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPharmacyActionPerformed

    private void btnDiagnosticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticsActionPerformed
        // TODO add your handling code here:
        DiagnosticsLoginJFrame d1 = new DiagnosticsLoginJFrame(this.applicationSystem, this.userAccount);
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDiagnosticsActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbulance;
    private javax.swing.JButton btnDiagnostics;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPharmacy;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

 
}
