/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AmbulanceDriver;

import Ambulance.Driver;
import UI.DiagnosticsSystemAdmin.*;
import UI.AmbulanceSystemAdmin.*;
import UI.SystemAdmin.*;
import ApplicationSystem.ApplicationSystem;
import Hospital.Doctor;
import Patient.AmbulanceRequest;
import Patient.Patient;
import User.UserAccount;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rushita
 */
public class DriverVehicleRequest extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    Driver driver;
    DefaultTableModel RequestTableModel;
    DefaultTableModel DoctorTableModel;
    public DriverVehicleRequest(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.applicationSystem = applicationSystem;
        this.driver = (Driver) userAccount;
        this.RequestTableModel = (DefaultTableModel) tblPatient.getModel();
        this.DoctorTableModel = (DefaultTableModel) tblDoctor.getModel();
        PopulateTable();
        PopulateDoctor();
        tblPatient.setDefaultRenderer(Object.class, new MyCellRenderer());
        tblDoctor.setDefaultRenderer(Object.class, new MyCellRenderer());
    }
    
     private class MyCellRenderer extends DefaultTableCellRenderer {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (row % 2 == 0) {
                c.setBackground(new Color(204, 204, 255)); 
            } else {
                c.setBackground(new Color(204, 204, 255)); 
            }
            return c;
        }
    }
    
    public void PopulateTable(){
        RequestTableModel.setRowCount(0);
        
        for(AmbulanceRequest ar : driver.getAmbulanceRequestDirectory().getAmbulanceRequestDetailsList()){
            Object rows[] = new Object[2];
            rows[0] = ar.getPatientDetails().getUserName();
            rows[1] = ar.getPatientAddress();
            
            
            RequestTableModel.addRow(rows);
        }
    }
    
    public void PopulateDoctor(){
        DoctorTableModel.setRowCount(0);
        
        for(Doctor dr : applicationSystem.getHospitalDirectory().getDoctorRegistry().getDoctorUserAccountList()){
            Object rows[] = new Object[1];
            rows[0] = dr.getUserName();
            
            
            
            DoctorTableModel.addRow(rows);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVehicleRequest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        btnDropoff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 16, 151));

        lblVehicleRequest.setBackground(new java.awt.Color(54, 125, 118));
        lblVehicleRequest.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        lblVehicleRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblVehicleRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleRequest.setText("VEHICLE'S REQUESTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVehicleRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblVehicleRequest)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatient);
        if (tblPatient.getColumnModel().getColumnCount() > 0) {
            tblPatient.getColumnModel().getColumn(0).setHeaderValue("Patient");
            tblPatient.getColumnModel().getColumn(1).setHeaderValue("Address");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 580, 220));

        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDoctor);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 530, 220));

        btnDropoff.setBackground(new java.awt.Color(204, 204, 255));
        btnDropoff.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        btnDropoff.setText("DROP OFF");
        btnDropoff.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDropoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropoffActionPerformed(evt);
            }
        });
        add(btnDropoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 120, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/ambulance (1).gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 950, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDropoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropoffActionPerformed
        // TODO add your handling code here:
        int row = tblPatient.getSelectedRow();
        int doctorrow = tblDoctor.getSelectedRow();

        if(row == -1)
        {
            JOptionPane.showMessageDialog(null,"Please select a Patient", "Select Warning", 2);
            return;
        }

        if(doctorrow == -1)
        {
            JOptionPane.showMessageDialog(null,"Please select a Doctor", "Select Warning", 2);
            return;

        }

        AmbulanceRequest ar = driver.getAmbulanceRequestDirectory().getAmbulanceRequestDetailsList().get(row);
        Patient patient = ar.getPatientDetails();
        Doctor doctor = applicationSystem.getHospitalDirectory().getDoctorRegistry().getDoctorUserAccountList().get(doctorrow);

        ar.getAssignedVehiclesDetails().setStatus("Available");
        doctor.getPatientDirectoryDetail().getPatientDetailList().add(patient);
        driver.increaseTrip();
        driver.getAmbulanceRequestDirectory().getAmbulanceRequestDetailsList().remove(row);
        JOptionPane.showMessageDialog(null, "Succesfully dropped of Patient");
    }//GEN-LAST:event_btnDropoffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDropoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblVehicleRequest;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables
}
