/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AmbulanceDriver;

import Ambulance.Driver;
import Ambulance.Vehicle;
import UI.DiagnosticsSystemAdmin.*;
import UI.AmbulanceSystemAdmin.*;
import UI.SystemAdmin.*;
import ApplicationSystem.ApplicationSystem;
import User.UserAccount;

/**
 *
 * @author rushita
 */
public class DriverDashboard extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    ApplicationSystem applicationSystem;
    Driver  driver;
    public DriverDashboard(ApplicationSystem applicationSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.applicationSystem = applicationSystem;
        this.driver =  (Driver) userAccount;
        this.populateVehicle();
        this.populateTrips();
        this.populateRevenue();
    }
    
    public void populateVehicle()
    {
        
        Vehicle vehicle = this.applicationSystem.getAmbulanceDirectory().getAssignedAmbulance(driver);
        String name = "Not yet Assigned";
        
        if(vehicle != null)
        {
            name = vehicle.getName();
        }
        
        this.jLabel2.setText(name);
        
    }
    
    public void populateTrips()
    {
        
        jLabel4.setText(String.valueOf(driver.getTrips()));
        
    }
    
    public void populateRevenue()
    {
        
        
         jLabel6.setText(String.valueOf(driver.getTrips() * 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboard = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblTotalTrips = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVehicle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard.setBackground(new java.awt.Color(56, 16, 151));

        jLabel14.setBackground(new java.awt.Color(54, 125, 118));
        jLabel14.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DASHBOARD");

        javax.swing.GroupLayout lblDashboardLayout = new javax.swing.GroupLayout(lblDashboard);
        lblDashboard.setLayout(lblDashboardLayout);
        lblDashboardLayout.setHorizontalGroup(
            lblDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lblDashboardLayout.setVerticalGroup(
            lblDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDashboardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        lblTotalTrips.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblTotalTrips.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalTrips.setText("TOTAL TRIPS :");
        add(lblTotalTrips, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 160, 30));

        jLabel4.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 118, 125));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 168, 32));

        lblTotalRevenue.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRevenue.setText("TOTAL REVENUE :");
        add(lblTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, 32));

        jLabel6.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 118, 125));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 168, 32));

        lblVehicle.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        lblVehicle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVehicle.setText("VEHICLE :");
        add(lblVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 150, 30));

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 118, 125));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 169, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/vector-cartoon-van-medical-car-driver-man-illustration-isolated-white-background-ambulance-vehicle-flat-style-auto-103706353.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 1000, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel lblDashboard;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblTotalTrips;
    private javax.swing.JLabel lblVehicle;
    // End of variables declaration//GEN-END:variables
}
